"""Initial alter statements

Revision ID: 1ed43776064f
Revises: ff7e7ae6d711
Create Date: 2017-04-23 19:06:40.644549

"""


# revision identifiers, used by Alembic.
revision = '1ed43776064f'
down_revision = 'ff7e7ae6d711'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_leader', 'group', 'attendee', ['leader_id'], ['id'], use_alter=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_leader', 'group', type_='foreignkey')
    ### end Alembic commands ###
