"""Adding hotel lottery awards

Revision ID: 21cb18083129
Revises: 6d8333eaf58a
Create Date: 2025-05-14 05:31:58.802292

"""


# revision identifiers, used by Alembic.
revision = '21cb18083129'
down_revision = '6d8333eaf58a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



try:
    is_sqlite = op.get_context().dialect.name == 'sqlite'
except Exception:
    is_sqlite = False

if is_sqlite:
    op.get_context().connection.execute('PRAGMA foreign_keys=ON;')
    utcnow_server_default = "(datetime('now', 'utc'))"
else:
    utcnow_server_default = "timezone('utc', current_timestamp)"

def sqlite_column_reflect_listener(inspector, table, column_info):
    """Adds parenthesis around SQLite datetime defaults for utcnow."""
    if column_info['default'] == "datetime('now', 'utc')":
        column_info['default'] = utcnow_server_default

sqlite_reflect_kwargs = {
    'listeners': [('column_reflect', sqlite_column_reflect_listener)]
}

# ===========================================================================
# HOWTO: Handle alter statements in SQLite
#
# def upgrade():
#     if is_sqlite:
#         with op.batch_alter_table('table_name', reflect_kwargs=sqlite_reflect_kwargs) as batch_op:
#             batch_op.alter_column('column_name', type_=sa.Unicode(), server_default='', nullable=False)
#     else:
#         op.alter_column('table_name', 'column_name', type_=sa.Unicode(), server_default='', nullable=False)
#
# ===========================================================================


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_attendee_creator_id_attendee', 'attendee', type_='foreignkey')
    op.create_foreign_key(op.f('fk_attendee_creator_id_attendee'), 'attendee', 'attendee', ['creator_id'], ['id'], ondelete='set null')
    op.add_column('lottery_application', sa.Column('assigned_hotel', sa.Integer(), nullable=True))
    op.add_column('lottery_application', sa.Column('assigned_room_type', sa.Integer(), nullable=True))
    op.add_column('lottery_application', sa.Column('assigned_suite_type', sa.Integer(), nullable=True))
    op.add_column('lottery_application', sa.Column('deposit_cutoff_date', sa.Date(), nullable=True))
    op.add_column('lottery_application', sa.Column('lottery_name', sa.Unicode(), server_default='', nullable=False))
    op.add_column('lottery_application', sa.Column('booking_url', sa.Unicode(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lottery_application', 'booking_url')
    op.drop_column('lottery_application', 'lottery_name')
    op.drop_column('lottery_application', 'deposit_cutoff_date')
    op.drop_column('lottery_application', 'assigned_suite_type')
    op.drop_column('lottery_application', 'assigned_room_type')
    op.drop_column('lottery_application', 'assigned_hotel')
    op.drop_constraint(op.f('fk_attendee_creator_id_attendee'), 'attendee', type_='foreignkey')
    op.create_foreign_key('fk_attendee_creator_id_attendee', 'attendee', 'attendee', ['creator_id'], ['id'])
    # ### end Alembic commands ###
