"""Hotel lottery system

Revision ID: 45ee9a3c0089
Revises: 4df6bfee2c69
Create Date: 2026-04-11 04:55:31.716206

"""


# revision identifiers, used by Alembic.
revision = '45ee9a3c0089'
down_revision = '4df6bfee2c69'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


try:
    is_sqlite = op.get_context().dialect.name == 'sqlite'
except Exception:
    is_sqlite = False

if is_sqlite:
    op.get_context().connection.execute('PRAGMA foreign_keys=ON;')
    utcnow_server_default = "(datetime('now', 'utc'))"
else:
    utcnow_server_default = "timezone('utc', current_timestamp)"

def sqlite_column_reflect_listener(inspector, table, column_info):
    """Adds parenthesis around SQLite datetime defaults for utcnow."""
    if column_info['default'] == "datetime('now', 'utc')":
        column_info['default'] = utcnow_server_default

sqlite_reflect_kwargs = {
    'listeners': [('column_reflect', sqlite_column_reflect_listener)]
}

# ===========================================================================
# HOWTO: Handle alter statements in SQLite
#
# def upgrade():
#     if is_sqlite:
#         with op.batch_alter_table('table_name', reflect_kwargs=sqlite_reflect_kwargs) as batch_op:
#             batch_op.alter_column('column_name', type_=sa.Unicode(), server_default='', nullable=False)
#     else:
#         op.alter_column('table_name', 'column_name', type_=sa.Unicode(), server_default='', nullable=False)
#
# ===========================================================================


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_partition',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_partition'))
    )
    op.create_table('lottery_hotel',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('export_name', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=False),
    sa.Column('description_right', sa.Unicode(), nullable=False),
    sa.Column('footnote', sa.Unicode(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lottery_hotel'))
    )
    op.create_table('lottery_room_type',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('export_name', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=False),
    sa.Column('description_right', sa.Unicode(), nullable=False),
    sa.Column('footnote', sa.Unicode(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('min_capacity', sa.Integer(), nullable=False),
    sa.Column('is_suite', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lottery_room_type'))
    )
    op.create_table('lottery_run',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('status', sa.Integer(), server_default='240058174', nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reverted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lottery_group', sa.Unicode(), nullable=False),
    sa.Column('lottery_type', sa.Unicode(), nullable=False),
    sa.Column('cutoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hotel_filter', sa.Unicode(), nullable=True),
    sa.Column('room_type_filter', sa.Unicode(), nullable=True),
    sa.Column('inventory_filter', sa.Unicode(), nullable=True),
    sa.Column('partition_filter', sa.Unicode(), nullable=True),
    sa.Column('entries_considered', sa.Integer(), nullable=False),
    sa.Column('rooms_assigned', sa.Integer(), nullable=False),
    sa.Column('rooms_available_before', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lottery_run'))
    )
    op.create_table('hotel_export_log',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hotel_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('export_type', sa.Unicode(), nullable=False),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exported_by', sa.Unicode(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Unicode(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['lottery_hotel.id'], name=op.f('fk_hotel_export_log_hotel_id_lottery_hotel')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotel_export_log'))
    )
    op.create_table('hotel_room_inventory',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hotel_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('room_type_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('suite_type_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('min_capacity', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('is_suite', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('vault_reference', sa.Unicode(), nullable=True),
    sa.Column('info_url', sa.Unicode(), nullable=False),
    sa.Column('price', sa.Unicode(), nullable=False),
    sa.Column('staff_price', sa.Unicode(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['lottery_hotel.id'], name=op.f('fk_hotel_room_inventory_hotel_id_lottery_hotel')),
    sa.ForeignKeyConstraint(['room_type_id'], ['lottery_room_type.id'], name=op.f('fk_hotel_room_inventory_room_type_id_lottery_room_type')),
    sa.ForeignKeyConstraint(['suite_type_id'], ['lottery_room_type.id'], name=op.f('fk_hotel_room_inventory_suite_type_id_lottery_room_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotel_room_inventory'))
    )
    op.create_table('inventory_night_quantity',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inventory_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('night_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['hotel_room_inventory.id'], name=op.f('fk_inventory_night_quantity_inventory_id_hotel_room_inventory')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_night_quantity')),
    sa.UniqueConstraint('inventory_id', 'night_date', name='uq_inventory_night')
    )
    op.create_table('inventory_partition_block',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('partition_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('inventory_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['hotel_room_inventory.id'], name=op.f('fk_inventory_partition_block_inventory_id_hotel_room_inventory')),
    sa.ForeignKeyConstraint(['partition_id'], ['inventory_partition.id'], name=op.f('fk_inventory_partition_block_partition_id_inventory_partition')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_partition_block')),
    sa.UniqueConstraint('partition_id', 'inventory_id', name='uq_partition_inventory')
    )
    op.add_column('lottery_application', sa.Column('assigned_inventory_id', sa.Uuid(as_uuid=False), nullable=True))
    op.add_column('lottery_application', sa.Column('partition_id', sa.Uuid(as_uuid=False), nullable=True))
    op.add_column('lottery_application', sa.Column('export_locked', sa.Boolean(), nullable=False))
    op.add_column('lottery_application', sa.Column('invite_token', sa.Unicode(), nullable=False))
    op.add_column('lottery_application', sa.Column('invited_by_id', sa.Uuid(as_uuid=False), nullable=True))
    op.add_column('lottery_application', sa.Column('invite_status', sa.Integer(), server_default='117453886', nullable=False))
    op.add_column('lottery_application', sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lottery_application', sa.Column('cc_token', sa.Unicode(), nullable=True))
    op.add_column('lottery_application', sa.Column('cc_last_four', sa.Unicode(), nullable=True))
    op.add_column('lottery_application', sa.Column('cc_card_type', sa.Unicode(), nullable=True))
    op.add_column('lottery_application', sa.Column('cc_card_holder', sa.Unicode(), nullable=True))
    op.add_column('lottery_application', sa.Column('cc_card_expiry', sa.Unicode(), nullable=True))
    op.add_column('lottery_application', sa.Column('cc_issuer_brand', sa.Unicode(), nullable=True))
    op.add_column('lottery_application', sa.Column('cc_issuer_bank', sa.Unicode(), nullable=True))
    op.add_column('lottery_application', sa.Column('cc_issuer_country', sa.Unicode(), nullable=True))
    op.add_column('lottery_application', sa.Column('cc_issuer_card_type', sa.Unicode(), nullable=True))
    op.add_column('lottery_application', sa.Column('cc_issuer_card_level', sa.Unicode(), nullable=True))
    op.add_column('lottery_application', sa.Column('cc_captured_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lottery_application', sa.Column('address1', sa.Unicode(), nullable=False))
    op.add_column('lottery_application', sa.Column('address2', sa.Unicode(), nullable=False))
    op.add_column('lottery_application', sa.Column('city', sa.Unicode(), nullable=False))
    op.add_column('lottery_application', sa.Column('region', sa.Unicode(), nullable=False))
    op.add_column('lottery_application', sa.Column('zip_code', sa.Unicode(), nullable=False))
    op.add_column('lottery_application', sa.Column('country', sa.Unicode(), nullable=False))
    op.add_column('lottery_application', sa.Column('hotel_confirmation_number', sa.Unicode(), nullable=True))
    op.add_column('lottery_application', sa.Column('special_requests', sa.Unicode(), nullable=False))
    op.add_column('lottery_application', sa.Column('hotel_rewards_number', sa.Unicode(), nullable=False))
    op.add_column('lottery_application', sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lottery_application', sa.Column('lottery_run_id', sa.Uuid(as_uuid=False), nullable=True))
    op.create_foreign_key(op.f('fk_lottery_application_invited_by_id_lottery_application'), 'lottery_application', 'lottery_application', ['invited_by_id'], ['id'])
    op.create_foreign_key(op.f('fk_lottery_application_assigned_inventory_id_hotel_room_inventory'), 'lottery_application', 'hotel_room_inventory', ['assigned_inventory_id'], ['id'])
    op.create_foreign_key(op.f('fk_lottery_application_lottery_run_id_lottery_run'), 'lottery_application', 'lottery_run', ['lottery_run_id'], ['id'])
    op.create_foreign_key(op.f('fk_lottery_application_partition_id_inventory_partition'), 'lottery_application', 'inventory_partition', ['partition_id'], ['id'])
    op.drop_column('lottery_application', 'final_status_hidden')
    op.drop_column('lottery_application', 'booking_url_hidden')
    op.drop_column('lottery_application', 'assigned_room_type')
    op.drop_column('lottery_application', 'assigned_suite_type')
    op.drop_column('lottery_application', 'assigned_hotel')
    op.drop_column('lottery_application', 'selection_priorities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lottery_application', sa.Column('selection_priorities', sa.Unicode(), server_default='', nullable=False))
    op.add_column('lottery_application', sa.Column('assigned_hotel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lottery_application', sa.Column('assigned_suite_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lottery_application', sa.Column('assigned_room_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lottery_application', sa.Column('booking_url_hidden', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('lottery_application', sa.Column('final_status_hidden', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_lottery_application_partition_id_inventory_partition'), 'lottery_application', type_='foreignkey')
    op.drop_constraint(op.f('fk_lottery_application_lottery_run_id_lottery_run'), 'lottery_application', type_='foreignkey')
    op.drop_constraint(op.f('fk_lottery_application_assigned_inventory_id_hotel_room_inventory'), 'lottery_application', type_='foreignkey')
    op.drop_constraint(op.f('fk_lottery_application_invited_by_id_lottery_application'), 'lottery_application', type_='foreignkey')
    op.drop_column('lottery_application', 'lottery_run_id')
    op.drop_column('lottery_application', 'last_modified_at')
    op.drop_column('lottery_application', 'hotel_rewards_number')
    op.drop_column('lottery_application', 'special_requests')
    op.drop_column('lottery_application', 'hotel_confirmation_number')
    op.drop_column('lottery_application', 'country')
    op.drop_column('lottery_application', 'zip_code')
    op.drop_column('lottery_application', 'region')
    op.drop_column('lottery_application', 'city')
    op.drop_column('lottery_application', 'address2')
    op.drop_column('lottery_application', 'address1')
    op.drop_column('lottery_application', 'cc_captured_at')
    op.drop_column('lottery_application', 'cc_issuer_card_level')
    op.drop_column('lottery_application', 'cc_issuer_card_type')
    op.drop_column('lottery_application', 'cc_issuer_country')
    op.drop_column('lottery_application', 'cc_issuer_bank')
    op.drop_column('lottery_application', 'cc_issuer_brand')
    op.drop_column('lottery_application', 'cc_card_expiry')
    op.drop_column('lottery_application', 'cc_card_holder')
    op.drop_column('lottery_application', 'cc_card_type')
    op.drop_column('lottery_application', 'cc_last_four')
    op.drop_column('lottery_application', 'cc_token')
    op.drop_column('lottery_application', 'invite_expires_at')
    op.drop_column('lottery_application', 'invite_status')
    op.drop_column('lottery_application', 'invited_by_id')
    op.drop_column('lottery_application', 'invite_token')
    op.drop_column('lottery_application', 'export_locked')
    op.drop_column('lottery_application', 'partition_id')
    op.drop_column('lottery_application', 'assigned_inventory_id')
    op.drop_table('inventory_partition_block')
    op.drop_table('inventory_night_quantity')
    op.drop_table('hotel_room_inventory')
    op.drop_table('hotel_export_log')
    op.drop_table('lottery_run')
    op.drop_table('lottery_room_type')
    op.drop_table('lottery_hotel')
    op.drop_table('inventory_partition')
    # ### end Alembic commands ###
