"""Add tracking for external services to Uber objects

Revision ID: 5f6cb43ef3ca
Revises: 37f79e6ccee7
Create Date: 2024-06-12 06:05:15.093725

"""


# revision identifiers, used by Alembic.
revision = '5f6cb43ef3ca'
down_revision = '37f79e6ccee7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


try:
    is_sqlite = op.get_context().dialect.name == 'sqlite'
except Exception:
    is_sqlite = False

if is_sqlite:
    op.get_context().connection.execute('PRAGMA foreign_keys=ON;')
    utcnow_server_default = "(datetime('now', 'utc'))"
else:
    utcnow_server_default = "timezone('utc', current_timestamp)"

def sqlite_column_reflect_listener(inspector, table, column_info):
    """Adds parenthesis around SQLite datetime defaults for utcnow."""
    if column_info['default'] == "datetime('now', 'utc')":
        column_info['default'] = utcnow_server_default

sqlite_reflect_kwargs = {
    'listeners': [('column_reflect', sqlite_column_reflect_listener)]
}

# ===========================================================================
# HOWTO: Handle alter statements in SQLite
#
# def upgrade():
#     if is_sqlite:
#         with op.batch_alter_table('table_name', reflect_kwargs=sqlite_reflect_kwargs) as batch_op:
#             batch_op.alter_column('column_name', type_=sa.Unicode(), server_default='', nullable=False)
#     else:
#         op.alter_column('table_name', 'column_name', type_=sa.Unicode(), server_default='', nullable=False)
#
# ===========================================================================


def upgrade():
    op.add_column('access_group', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('access_group', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('access_group', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('access_group', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('admin_account', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('admin_account', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('admin_account', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('admin_account', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('api_job', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('api_job', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('api_job', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('api_job', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('api_token', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('api_token', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('api_token', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('api_token', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('arbitrary_charge', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('arbitrary_charge', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('arbitrary_charge', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('arbitrary_charge', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('art_show_agent_code', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('art_show_agent_code', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('art_show_agent_code', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('art_show_agent_code', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('art_show_application', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('art_show_application', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('art_show_application', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('art_show_application', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('art_show_bidder', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('art_show_bidder', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('art_show_bidder', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('art_show_bidder', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('art_show_payment', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('art_show_payment', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('art_show_payment', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('art_show_payment', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('art_show_piece', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('art_show_piece', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('art_show_piece', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('art_show_piece', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('art_show_receipt', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('art_show_receipt', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('art_show_receipt', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('art_show_receipt', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('assigned_panelist', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('assigned_panelist', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('assigned_panelist', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('assigned_panelist', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('attendee', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('attendee', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('attendee', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('attendee', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('attendee_account', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('attendee_account', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('attendee_account', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('attendee_account', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('attendee_tournament', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('attendee_tournament', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('attendee_tournament', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('attendee_tournament', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('attraction', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('attraction', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('attraction', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('attraction', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('attraction_event', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('attraction_event', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('attraction_event', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('attraction_event', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('attraction_feature', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('attraction_feature', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('attraction_feature', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('attraction_feature', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('attraction_notification', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('attraction_notification', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('attraction_notification', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('attraction_notification', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('attraction_notification_reply', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('attraction_notification_reply', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('attraction_notification_reply', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('attraction_notification_reply', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('attraction_signup', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('attraction_signup', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('attraction_signup', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('attraction_signup', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('automated_email', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('automated_email', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('automated_email', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('automated_email', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('department', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('department', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('department', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('department', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('dept_checklist_item', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('dept_checklist_item', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('dept_checklist_item', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('dept_checklist_item', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('dept_membership', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('dept_membership', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('dept_membership', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('dept_membership', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('dept_membership_request', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('dept_membership_request', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('dept_membership_request', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('dept_membership_request', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('dept_role', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('dept_role', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('dept_role', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('dept_role', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('email', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('email', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('email', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('email', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('event', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('event', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('event', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('event', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('event_feedback', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('event_feedback', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('event_feedback', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('event_feedback', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('food_restrictions', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('food_restrictions', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('food_restrictions', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('food_restrictions', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('group', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('group', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('group', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('group', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_autograph', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_autograph', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_autograph', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_autograph', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_bio', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_bio', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_bio', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_bio', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_charity', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_charity', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_charity', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_charity', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_detailed_travel_plan', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_detailed_travel_plan', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_detailed_travel_plan', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_detailed_travel_plan', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_group', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_group', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_group', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_group', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_hospitality', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_hospitality', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_hospitality', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_hospitality', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_info', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_info', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_info', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_info', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_interview', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_interview', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_interview', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_interview', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_merch', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_merch', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_merch', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_merch', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_panel', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_panel', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_panel', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_panel', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_stage_plot', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_stage_plot', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_stage_plot', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_stage_plot', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_taxes', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_taxes', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_taxes', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_taxes', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_travel_plans', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_travel_plans', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('guest_travel_plans', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('guest_travel_plans', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('hotel_requests', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('hotel_requests', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('hotel_requests', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('hotel_requests', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('indie_developer', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('indie_developer', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('indie_developer', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('indie_developer', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('indie_game', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('indie_game', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('indie_game', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('indie_game', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('indie_game_code', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('indie_game_code', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('indie_game_code', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('indie_game_code', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('indie_game_image', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('indie_game_image', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('indie_game_image', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('indie_game_image', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('indie_game_review', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('indie_game_review', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('indie_game_review', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('indie_game_review', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('indie_judge', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('indie_judge', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('indie_judge', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('indie_judge', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('indie_studio', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('indie_studio', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('indie_studio', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('indie_studio', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('job', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('job', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('job', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('job', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('m_points_for_cash', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('m_points_for_cash', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('m_points_for_cash', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('m_points_for_cash', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('marketplace_application', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('marketplace_application', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('marketplace_application', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('marketplace_application', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('merch_discount', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('merch_discount', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('merch_discount', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('merch_discount', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('merch_pickup', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('merch_pickup', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('merch_pickup', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('merch_pickup', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('mits_applicant', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('mits_applicant', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('mits_applicant', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('mits_applicant', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('mits_document', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('mits_document', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('mits_document', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('mits_document', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('mits_game', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('mits_game', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('mits_game', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('mits_game', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('mits_panel_application', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('mits_panel_application', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('mits_panel_application', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('mits_panel_application', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('mits_picture', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('mits_picture', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('mits_picture', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('mits_picture', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('mits_team', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('mits_team', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('mits_team', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('mits_team', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('mits_times', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('mits_times', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('mits_times', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('mits_times', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('model_receipt', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('model_receipt', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('model_receipt', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('model_receipt', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('no_shirt', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('no_shirt', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('no_shirt', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('no_shirt', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('old_m_point_exchange', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('old_m_point_exchange', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('old_m_point_exchange', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('old_m_point_exchange', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('page_view_tracking', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('page_view_tracking', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('page_view_tracking', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('page_view_tracking', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('panel_applicant', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('panel_applicant', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('panel_applicant', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('panel_applicant', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('panel_application', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('panel_application', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('panel_application', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('panel_application', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('password_reset', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('password_reset', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('password_reset', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('password_reset', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('print_job', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('print_job', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('print_job', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('print_job', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('promo_code', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('promo_code', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('promo_code', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('promo_code', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('promo_code_group', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('promo_code_group', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('promo_code_group', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('promo_code_group', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('promo_code_word', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('promo_code_word', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('promo_code_word', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('promo_code_word', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('receipt_info', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('receipt_info', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('receipt_info', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('receipt_info', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('receipt_item', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('receipt_item', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('receipt_item', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('receipt_item', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('receipt_transaction', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('receipt_transaction', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('receipt_transaction', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('receipt_transaction', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('report_tracking', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('report_tracking', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('report_tracking', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('report_tracking', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('room', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('room', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('room', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('room_assignment', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('room_assignment', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('room_assignment', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('room_assignment', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('sale', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('sale', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('sale', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('sale', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('shift', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('shift', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('shift', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('shift', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('signed_document', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('signed_document', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('signed_document', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('signed_document', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('tabletop_checkout', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('tabletop_checkout', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('tabletop_checkout', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('tabletop_checkout', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('tabletop_game', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('tabletop_game', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('tabletop_game', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('tabletop_game', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('terminal_settlement', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('terminal_settlement', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('terminal_settlement', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('terminal_settlement', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('tracking', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('tracking', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('tracking', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('tracking', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('txn_request_tracking', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('txn_request_tracking', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('txn_request_tracking', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('txn_request_tracking', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('watch_list', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('watch_list', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('watch_list', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('watch_list', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('workstation_assignment', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('workstation_assignment', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    op.add_column('workstation_assignment', sa.Column('external_id', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('workstation_assignment', sa.Column('last_synced', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))


def downgrade():
    op.drop_column('workstation_assignment', 'last_synced')
    op.drop_column('workstation_assignment', 'external_id')
    op.drop_column('workstation_assignment', 'last_updated')
    op.drop_column('workstation_assignment', 'created')
    op.drop_column('watch_list', 'last_synced')
    op.drop_column('watch_list', 'external_id')
    op.drop_column('watch_list', 'last_updated')
    op.drop_column('watch_list', 'created')
    op.drop_column('txn_request_tracking', 'last_synced')
    op.drop_column('txn_request_tracking', 'external_id')
    op.drop_column('txn_request_tracking', 'last_updated')
    op.drop_column('txn_request_tracking', 'created')
    op.drop_column('tracking', 'last_synced')
    op.drop_column('tracking', 'external_id')
    op.drop_column('tracking', 'last_updated')
    op.drop_column('tracking', 'created')
    op.drop_column('terminal_settlement', 'last_synced')
    op.drop_column('terminal_settlement', 'external_id')
    op.drop_column('terminal_settlement', 'last_updated')
    op.drop_column('terminal_settlement', 'created')
    op.drop_column('tabletop_game', 'last_synced')
    op.drop_column('tabletop_game', 'external_id')
    op.drop_column('tabletop_game', 'last_updated')
    op.drop_column('tabletop_game', 'created')
    op.drop_column('tabletop_checkout', 'last_synced')
    op.drop_column('tabletop_checkout', 'external_id')
    op.drop_column('tabletop_checkout', 'last_updated')
    op.drop_column('tabletop_checkout', 'created')
    op.drop_column('signed_document', 'last_synced')
    op.drop_column('signed_document', 'external_id')
    op.drop_column('signed_document', 'last_updated')
    op.drop_column('signed_document', 'created')
    op.drop_column('shift', 'last_synced')
    op.drop_column('shift', 'external_id')
    op.drop_column('shift', 'last_updated')
    op.drop_column('shift', 'created')
    op.drop_column('sale', 'last_synced')
    op.drop_column('sale', 'external_id')
    op.drop_column('sale', 'last_updated')
    op.drop_column('sale', 'created')
    op.drop_column('room_assignment', 'last_synced')
    op.drop_column('room_assignment', 'external_id')
    op.drop_column('room_assignment', 'last_updated')
    op.drop_column('room_assignment', 'created')
    op.drop_column('room', 'last_synced')
    op.drop_column('room', 'external_id')
    op.drop_column('room', 'last_updated')
    op.drop_column('report_tracking', 'last_synced')
    op.drop_column('report_tracking', 'external_id')
    op.drop_column('report_tracking', 'last_updated')
    op.drop_column('report_tracking', 'created')
    op.drop_column('receipt_transaction', 'last_synced')
    op.drop_column('receipt_transaction', 'external_id')
    op.drop_column('receipt_transaction', 'last_updated')
    op.drop_column('receipt_transaction', 'created')
    op.drop_column('receipt_item', 'last_synced')
    op.drop_column('receipt_item', 'external_id')
    op.drop_column('receipt_item', 'last_updated')
    op.drop_column('receipt_item', 'created')
    op.drop_column('receipt_info', 'last_synced')
    op.drop_column('receipt_info', 'external_id')
    op.drop_column('receipt_info', 'last_updated')
    op.drop_column('receipt_info', 'created')
    op.drop_column('promo_code_word', 'last_synced')
    op.drop_column('promo_code_word', 'external_id')
    op.drop_column('promo_code_word', 'last_updated')
    op.drop_column('promo_code_word', 'created')
    op.drop_column('promo_code_group', 'last_synced')
    op.drop_column('promo_code_group', 'external_id')
    op.drop_column('promo_code_group', 'last_updated')
    op.drop_column('promo_code_group', 'created')
    op.drop_column('promo_code', 'last_synced')
    op.drop_column('promo_code', 'external_id')
    op.drop_column('promo_code', 'last_updated')
    op.drop_column('promo_code', 'created')
    op.drop_column('print_job', 'last_synced')
    op.drop_column('print_job', 'external_id')
    op.drop_column('print_job', 'last_updated')
    op.drop_column('print_job', 'created')
    op.drop_column('password_reset', 'last_synced')
    op.drop_column('password_reset', 'external_id')
    op.drop_column('password_reset', 'last_updated')
    op.drop_column('password_reset', 'created')
    op.drop_column('panel_application', 'last_synced')
    op.drop_column('panel_application', 'external_id')
    op.drop_column('panel_application', 'last_updated')
    op.drop_column('panel_application', 'created')
    op.drop_column('panel_applicant', 'last_synced')
    op.drop_column('panel_applicant', 'external_id')
    op.drop_column('panel_applicant', 'last_updated')
    op.drop_column('panel_applicant', 'created')
    op.drop_column('page_view_tracking', 'last_synced')
    op.drop_column('page_view_tracking', 'external_id')
    op.drop_column('page_view_tracking', 'last_updated')
    op.drop_column('page_view_tracking', 'created')
    op.drop_column('old_m_point_exchange', 'last_synced')
    op.drop_column('old_m_point_exchange', 'external_id')
    op.drop_column('old_m_point_exchange', 'last_updated')
    op.drop_column('old_m_point_exchange', 'created')
    op.drop_column('no_shirt', 'last_synced')
    op.drop_column('no_shirt', 'external_id')
    op.drop_column('no_shirt', 'last_updated')
    op.drop_column('no_shirt', 'created')
    op.drop_column('model_receipt', 'last_synced')
    op.drop_column('model_receipt', 'external_id')
    op.drop_column('model_receipt', 'last_updated')
    op.drop_column('model_receipt', 'created')
    op.drop_column('mits_times', 'last_synced')
    op.drop_column('mits_times', 'external_id')
    op.drop_column('mits_times', 'last_updated')
    op.drop_column('mits_times', 'created')
    op.drop_column('mits_team', 'last_synced')
    op.drop_column('mits_team', 'external_id')
    op.drop_column('mits_team', 'last_updated')
    op.drop_column('mits_team', 'created')
    op.drop_column('mits_picture', 'last_synced')
    op.drop_column('mits_picture', 'external_id')
    op.drop_column('mits_picture', 'last_updated')
    op.drop_column('mits_picture', 'created')
    op.drop_column('mits_panel_application', 'last_synced')
    op.drop_column('mits_panel_application', 'external_id')
    op.drop_column('mits_panel_application', 'last_updated')
    op.drop_column('mits_panel_application', 'created')
    op.drop_column('mits_game', 'last_synced')
    op.drop_column('mits_game', 'external_id')
    op.drop_column('mits_game', 'last_updated')
    op.drop_column('mits_game', 'created')
    op.drop_column('mits_document', 'last_synced')
    op.drop_column('mits_document', 'external_id')
    op.drop_column('mits_document', 'last_updated')
    op.drop_column('mits_document', 'created')
    op.drop_column('mits_applicant', 'last_synced')
    op.drop_column('mits_applicant', 'external_id')
    op.drop_column('mits_applicant', 'last_updated')
    op.drop_column('mits_applicant', 'created')
    op.drop_column('merch_pickup', 'last_synced')
    op.drop_column('merch_pickup', 'external_id')
    op.drop_column('merch_pickup', 'last_updated')
    op.drop_column('merch_pickup', 'created')
    op.drop_column('merch_discount', 'last_synced')
    op.drop_column('merch_discount', 'external_id')
    op.drop_column('merch_discount', 'last_updated')
    op.drop_column('merch_discount', 'created')
    op.drop_column('marketplace_application', 'last_synced')
    op.drop_column('marketplace_application', 'external_id')
    op.drop_column('marketplace_application', 'last_updated')
    op.drop_column('marketplace_application', 'created')
    op.drop_column('m_points_for_cash', 'last_synced')
    op.drop_column('m_points_for_cash', 'external_id')
    op.drop_column('m_points_for_cash', 'last_updated')
    op.drop_column('m_points_for_cash', 'created')
    op.drop_column('job', 'last_synced')
    op.drop_column('job', 'external_id')
    op.drop_column('job', 'last_updated')
    op.drop_column('job', 'created')
    op.drop_column('indie_studio', 'last_synced')
    op.drop_column('indie_studio', 'external_id')
    op.drop_column('indie_studio', 'last_updated')
    op.drop_column('indie_studio', 'created')
    op.drop_column('indie_judge', 'last_synced')
    op.drop_column('indie_judge', 'external_id')
    op.drop_column('indie_judge', 'last_updated')
    op.drop_column('indie_judge', 'created')
    op.drop_column('indie_game_review', 'last_synced')
    op.drop_column('indie_game_review', 'external_id')
    op.drop_column('indie_game_review', 'last_updated')
    op.drop_column('indie_game_review', 'created')
    op.drop_column('indie_game_image', 'last_synced')
    op.drop_column('indie_game_image', 'external_id')
    op.drop_column('indie_game_image', 'last_updated')
    op.drop_column('indie_game_image', 'created')
    op.drop_column('indie_game_code', 'last_synced')
    op.drop_column('indie_game_code', 'external_id')
    op.drop_column('indie_game_code', 'last_updated')
    op.drop_column('indie_game_code', 'created')
    op.drop_column('indie_game', 'last_synced')
    op.drop_column('indie_game', 'external_id')
    op.drop_column('indie_game', 'last_updated')
    op.drop_column('indie_game', 'created')
    op.drop_column('indie_developer', 'last_synced')
    op.drop_column('indie_developer', 'external_id')
    op.drop_column('indie_developer', 'last_updated')
    op.drop_column('indie_developer', 'created')
    op.drop_column('hotel_requests', 'last_synced')
    op.drop_column('hotel_requests', 'external_id')
    op.drop_column('hotel_requests', 'last_updated')
    op.drop_column('hotel_requests', 'created')
    op.drop_column('guest_travel_plans', 'last_synced')
    op.drop_column('guest_travel_plans', 'external_id')
    op.drop_column('guest_travel_plans', 'last_updated')
    op.drop_column('guest_travel_plans', 'created')
    op.drop_column('guest_taxes', 'last_synced')
    op.drop_column('guest_taxes', 'external_id')
    op.drop_column('guest_taxes', 'last_updated')
    op.drop_column('guest_taxes', 'created')
    op.drop_column('guest_stage_plot', 'last_synced')
    op.drop_column('guest_stage_plot', 'external_id')
    op.drop_column('guest_stage_plot', 'last_updated')
    op.drop_column('guest_stage_plot', 'created')
    op.drop_column('guest_panel', 'last_synced')
    op.drop_column('guest_panel', 'external_id')
    op.drop_column('guest_panel', 'last_updated')
    op.drop_column('guest_panel', 'created')
    op.drop_column('guest_merch', 'last_synced')
    op.drop_column('guest_merch', 'external_id')
    op.drop_column('guest_merch', 'last_updated')
    op.drop_column('guest_merch', 'created')
    op.drop_column('guest_interview', 'last_synced')
    op.drop_column('guest_interview', 'external_id')
    op.drop_column('guest_interview', 'last_updated')
    op.drop_column('guest_interview', 'created')
    op.drop_column('guest_info', 'last_synced')
    op.drop_column('guest_info', 'external_id')
    op.drop_column('guest_info', 'last_updated')
    op.drop_column('guest_info', 'created')
    op.drop_column('guest_hospitality', 'last_synced')
    op.drop_column('guest_hospitality', 'external_id')
    op.drop_column('guest_hospitality', 'last_updated')
    op.drop_column('guest_hospitality', 'created')
    op.drop_column('guest_group', 'last_synced')
    op.drop_column('guest_group', 'external_id')
    op.drop_column('guest_group', 'last_updated')
    op.drop_column('guest_group', 'created')
    op.drop_column('guest_detailed_travel_plan', 'last_synced')
    op.drop_column('guest_detailed_travel_plan', 'external_id')
    op.drop_column('guest_detailed_travel_plan', 'last_updated')
    op.drop_column('guest_detailed_travel_plan', 'created')
    op.drop_column('guest_charity', 'last_synced')
    op.drop_column('guest_charity', 'external_id')
    op.drop_column('guest_charity', 'last_updated')
    op.drop_column('guest_charity', 'created')
    op.drop_column('guest_bio', 'last_synced')
    op.drop_column('guest_bio', 'external_id')
    op.drop_column('guest_bio', 'last_updated')
    op.drop_column('guest_bio', 'created')
    op.drop_column('guest_autograph', 'last_synced')
    op.drop_column('guest_autograph', 'external_id')
    op.drop_column('guest_autograph', 'last_updated')
    op.drop_column('guest_autograph', 'created')
    op.drop_column('group', 'last_synced')
    op.drop_column('group', 'external_id')
    op.drop_column('group', 'last_updated')
    op.drop_column('group', 'created')
    op.drop_column('food_restrictions', 'last_synced')
    op.drop_column('food_restrictions', 'external_id')
    op.drop_column('food_restrictions', 'last_updated')
    op.drop_column('food_restrictions', 'created')
    op.drop_column('event_feedback', 'last_synced')
    op.drop_column('event_feedback', 'external_id')
    op.drop_column('event_feedback', 'last_updated')
    op.drop_column('event_feedback', 'created')
    op.drop_column('event', 'last_synced')
    op.drop_column('event', 'external_id')
    op.drop_column('event', 'last_updated')
    op.drop_column('event', 'created')
    op.drop_column('email', 'last_synced')
    op.drop_column('email', 'external_id')
    op.drop_column('email', 'last_updated')
    op.drop_column('email', 'created')
    op.drop_column('dept_role', 'last_synced')
    op.drop_column('dept_role', 'external_id')
    op.drop_column('dept_role', 'last_updated')
    op.drop_column('dept_role', 'created')
    op.drop_column('dept_membership_request', 'last_synced')
    op.drop_column('dept_membership_request', 'external_id')
    op.drop_column('dept_membership_request', 'last_updated')
    op.drop_column('dept_membership_request', 'created')
    op.drop_column('dept_membership', 'last_synced')
    op.drop_column('dept_membership', 'external_id')
    op.drop_column('dept_membership', 'last_updated')
    op.drop_column('dept_membership', 'created')
    op.drop_column('dept_checklist_item', 'last_synced')
    op.drop_column('dept_checklist_item', 'external_id')
    op.drop_column('dept_checklist_item', 'last_updated')
    op.drop_column('dept_checklist_item', 'created')
    op.drop_column('department', 'last_synced')
    op.drop_column('department', 'external_id')
    op.drop_column('department', 'last_updated')
    op.drop_column('department', 'created')
    op.drop_column('automated_email', 'last_synced')
    op.drop_column('automated_email', 'external_id')
    op.drop_column('automated_email', 'last_updated')
    op.drop_column('automated_email', 'created')
    op.drop_column('attraction_signup', 'last_synced')
    op.drop_column('attraction_signup', 'external_id')
    op.drop_column('attraction_signup', 'last_updated')
    op.drop_column('attraction_signup', 'created')
    op.drop_column('attraction_notification_reply', 'last_synced')
    op.drop_column('attraction_notification_reply', 'external_id')
    op.drop_column('attraction_notification_reply', 'last_updated')
    op.drop_column('attraction_notification_reply', 'created')
    op.drop_column('attraction_notification', 'last_synced')
    op.drop_column('attraction_notification', 'external_id')
    op.drop_column('attraction_notification', 'last_updated')
    op.drop_column('attraction_notification', 'created')
    op.drop_column('attraction_feature', 'last_synced')
    op.drop_column('attraction_feature', 'external_id')
    op.drop_column('attraction_feature', 'last_updated')
    op.drop_column('attraction_feature', 'created')
    op.drop_column('attraction_event', 'last_synced')
    op.drop_column('attraction_event', 'external_id')
    op.drop_column('attraction_event', 'last_updated')
    op.drop_column('attraction_event', 'created')
    op.drop_column('attraction', 'last_synced')
    op.drop_column('attraction', 'external_id')
    op.drop_column('attraction', 'last_updated')
    op.drop_column('attraction', 'created')
    op.drop_column('attendee_tournament', 'last_synced')
    op.drop_column('attendee_tournament', 'external_id')
    op.drop_column('attendee_tournament', 'last_updated')
    op.drop_column('attendee_tournament', 'created')
    op.drop_column('attendee_account', 'last_synced')
    op.drop_column('attendee_account', 'external_id')
    op.drop_column('attendee_account', 'last_updated')
    op.drop_column('attendee_account', 'created')
    op.drop_column('attendee', 'last_synced')
    op.drop_column('attendee', 'external_id')
    op.drop_column('attendee', 'last_updated')
    op.drop_column('attendee', 'created')
    op.drop_column('assigned_panelist', 'last_synced')
    op.drop_column('assigned_panelist', 'external_id')
    op.drop_column('assigned_panelist', 'last_updated')
    op.drop_column('assigned_panelist', 'created')
    op.drop_column('art_show_receipt', 'last_synced')
    op.drop_column('art_show_receipt', 'external_id')
    op.drop_column('art_show_receipt', 'last_updated')
    op.drop_column('art_show_receipt', 'created')
    op.drop_column('art_show_piece', 'last_synced')
    op.drop_column('art_show_piece', 'external_id')
    op.drop_column('art_show_piece', 'last_updated')
    op.drop_column('art_show_piece', 'created')
    op.drop_column('art_show_payment', 'last_synced')
    op.drop_column('art_show_payment', 'external_id')
    op.drop_column('art_show_payment', 'last_updated')
    op.drop_column('art_show_payment', 'created')
    op.drop_column('art_show_bidder', 'last_synced')
    op.drop_column('art_show_bidder', 'external_id')
    op.drop_column('art_show_bidder', 'last_updated')
    op.drop_column('art_show_bidder', 'created')
    op.drop_column('art_show_application', 'last_synced')
    op.drop_column('art_show_application', 'external_id')
    op.drop_column('art_show_application', 'last_updated')
    op.drop_column('art_show_application', 'created')
    op.drop_column('art_show_agent_code', 'last_synced')
    op.drop_column('art_show_agent_code', 'external_id')
    op.drop_column('art_show_agent_code', 'last_updated')
    op.drop_column('art_show_agent_code', 'created')
    op.drop_column('arbitrary_charge', 'last_synced')
    op.drop_column('arbitrary_charge', 'external_id')
    op.drop_column('arbitrary_charge', 'last_updated')
    op.drop_column('arbitrary_charge', 'created')
    op.drop_column('api_token', 'last_synced')
    op.drop_column('api_token', 'external_id')
    op.drop_column('api_token', 'last_updated')
    op.drop_column('api_token', 'created')
    op.drop_column('api_job', 'last_synced')
    op.drop_column('api_job', 'external_id')
    op.drop_column('api_job', 'last_updated')
    op.drop_column('api_job', 'created')
    op.drop_column('admin_account', 'last_synced')
    op.drop_column('admin_account', 'external_id')
    op.drop_column('admin_account', 'last_updated')
    op.drop_column('admin_account', 'created')
    op.drop_column('access_group', 'last_synced')
    op.drop_column('access_group', 'external_id')
    op.drop_column('access_group', 'last_updated')
    op.drop_column('access_group', 'created')
