# selects from all magfest databases, m6 thru m11

CREATE VIEW `m11`.`view_all_paying_attendees_all_magfests` AS

SELECT
11 as magfest_year,
v.`id`,
v.`admin_notes`,
v.`affiliate`,
v.`age_group`,
v.`amount_paid`,
v.`amount_refunded`,
v.`badge_num`,
v.`badge_type`,
v.`can_spam`,
v.`checked_in`,
v.`comments`,
v.`ec_phone`,
v.`email`,
v.`extra_merch` as extra_swag,
v.`first_name`,
v.`found_how`,
v.`group_id`,
v.`interests`,
v.`international`,
v.`last_name`,
v.`paid`,
v.`phone`,
v.`registered`,
v.`ribbon`,
0 as shirt,
v.`zip_code`
FROM view_allpayingattendees_m11 v

UNION ALL

SELECT
10 as magfest_year,
v.`id` + 1000000 as id,
v.`admin_notes`,
v.`affiliate`,
v.`age_group`,
v.`amount_paid`,
v.`amount_refunded`,
v.`badge_num`,
v.`badge_type`,
v.`can_spam`,
v.`checked_in`,
v.`comments`,
v.`ec_phone`,
v.`email`,
v.`extra_swag`,
v.`first_name`,
v.`found_how`,
v.`group_id`,
v.`interests`,
v.`international`,
v.`last_name`,
v.`paid`,
v.`phone`,
v.`registered`,
v.`ribbon`,
v.`shirt`,
v.`zip_code`
FROM view_allpayingattendees_m10 v

UNION ALL

SELECT
9 as magfest_year,
v.`id` + 900000 as id,
v.`admin_notes`,
v.`affiliate`,
v.`age_group`,
v.`amount_paid`,
v.`amount_refunded`,
v.`badge_num`,
v.`badge_type`,
v.`can_spam`,
v.`checked_in`,
v.`comments`,
v.`ec_phone`,
v.`email`,
v.`extra_swag`,
v.`first_name`,
v.`found_how`,
v.`group_id`,
v.`interests`,
v.`international`,
v.`last_name`,
v.`paid`,
v.`phone`,
v.`registered`,
v.`ribbon`,
v.`shirt`,
v.`zip_code`
FROM view_allpayingattendees_m9 v

UNION ALL

SELECT
8 as magfest_year,
v.`id` + 800000 as id,
v.`admin_notes`,
v.`affiliate`,
v.`age_group`,
v.`amount_paid`,
v.`amount_refunded`,
v.`badge_num`,
v.`badge_type`,
0 as can_spam,
v.`checked_in`,
v.`comments`,
v.`ec_phone`,
v.`email`,
v.`extra_swag`,
v.`first_name`,
v.`found_how`,
v.`group_id`,
v.`interests`,
v.`international`,
v.`last_name`,
v.`paid`,
v.`phone`,
v.`registered`,
0 as ribbon,
v.`shirt`,
v.`zip_code`
FROM view_allpayingattendees_m8 v

UNION ALL

SELECT
7 as magfest_year,
v.`id` + 700000 as id,
v.`admin_notes`,
'' as affiliate,
v.`age_group`,
v.`amount_paid`,
v.`amount_refunded`,
v.`badge_num`,
v.`badge_type`,
0 as `can_spam`, 
v.`checked_in`,
v.`comments`,
v.`ec_phone`,
v.`email`,
'' as `extra_swag`,
v.`first_name`,
v.`found_how`,
v.`group_id`,
v.`interests`,
v.`international`,
v.`last_name`,
v.`paid`,
v.`phone`,
v.`registered`,
0 as `ribbon`,
v.`shirt`,
v.`zip_code`
FROM view_allpayingattendees_m7 v

UNION ALL

SELECT
6 as magfest_year,
v.`id`+ 600000 as id,
v.`adminnotes` as admin_notes,
'' as affiliate,
v.`agegroup` as age_group,
v.`amountpaid` as amount_paid,
v.`refunded` as amount_refunded,
v.`badge_num`,
v.`badge_type`,
0 as `can_spam`,
v.`checkedin` as checked_in,
v.`comments`,
0 as ec_phone, 
v.`email`,
'' as `extra_swag`, 
v.`firstname` as first_name,
v.`foundhow` as found_how,
v.`business_id` as `group_id`, 
v.`camefor` as interests,
0 as international, 
v.`lastname` as last_name,
v.`paid`,
v.`phone`,
v.`registered`,
0 as `ribbon`,
v.`shirt`,
v.`zipcode` as zip_code
FROM view_allpayingattendees_m6 v;